# Use a imagem oficial do Node.js como base
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copie o package.json e o package-lock.json (ou yarn.lock)
COPY package.json package-lock.json ./

# Instale as dependências da aplicação
RUN npm install

# Copie o código da aplicação para o container
COPY . .

# Compile o TypeScript (caso precise)
RUN npm run build

# Exponha a porta em que o Vite irá rodar
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev"]
